### ISSUE TITLE
Supporting different code syntax libraries

### ISSUE THREAD

**Issue by CHHUM** [evbacher/gd2md-html#104]
I’m wondering if it would be possible to add support for prism.js for code blocks in HTML - Prism seems to be being used a lot now and it’s what we use at work.

I’m guessing this one of those things though where there are lots of syntax highlighting libraries and they are all a bit different.

Prism uses:
<pre><code class="language-typescript line-numbers”>

In the source code, use this code (replacing “typescript” with the language you are using, based on this list: https://prismjs.com/index.html)

And, obviously ends with </code></pre>

I can think of a couple of different ways of doing it.
Add a check box to say “output code for Prism.js”
Add some sort generic override for the way code blocks are handled - for example a pair of text box that, if not empty is used to set the opening and closing tags for code blocks.
In both cases it would be really nice if it could preserve the lang option as now.

Looking at the code you have a quite handy set of variables, so I’m thinking it wouldn’t be too hard to do, but I’m rushed off my feet at the moment so I thought I’d log this in case you had time to pick it up.  If not I’ll try and do it myself and then offer it back if you would like it but it might be a while until I can get to it; if you have the project set up and buildable I’m guessing it might be quicker.

Whilst I’m here this is great add-on by the way - I literally use it multiple times a week.

**Comment by evbacher** [comment]
I think that syntax highlighting libraries are usually applied when the page is rendered. It will depend on how your web server is set up. In any case, I don't think we'll attempt to support any particular syntax library during conversion.
