### ISSUE TITLE
Problem with exporting code samples

### ISSUE THREAD

**Issue by tjperry07** [evbacher/gd2md-html#106]
Code Blocks are not exported as markdown. Based on the features,https://github.com/evbacher/gd2md-html/wiki#features, I would expect the output to be:

~~~
```
public class HelloWorld {
  public static void main(String[] args) {
    System.out.println("Hello, World");
  }
}
```
~~~

Instead the output is the same as the input:

~~~
lang:java

public class HelloWorld {

  public static void main(String[] args) {

	System.out.println("Hello, World");

  }

}
~~~

Tested with multiple code samples, including the sample from the documentation .

![Screenshot from 2022-04-24 10-58-47](https://user-images.githubusercontent.com/5667652/164982668-abb33d51-7731-4127-8b60-2c7a245e173c.png)

**Comment by evbacher** [comment]
Is your code sample in a constant-width font (e.g., Courier, Consolas, Roboto Mono)? Otherwise, the converter does not know it's code.

**Comment by tjperry07** [comment]
Yup, that was the issue. Sorry about that, it was listed right in the doc I linked.

**Comment by evbacher** [comment]
No worries. I actually added a bit more information about the specific fonts so that it was more explicit, thanks to your bug. Glad it's working for you now.
