### ISSUE TITLE
Markdown output should pass markdownlint

### ISSUE THREAD

**Issue by galligan** [evbacher/gd2md-html#107]
## tl;dr

To maximize compatibility of exported markdown, gd2md should conform to [`markdownlint`](https://github.com/DavidAnson/markdownlint) conventions.

## Motivation

We're regularly using Google Docs to write and collaborate, and later export results to GitHub as issues, or as `.md` files to be included in a Docusaurus instance. Because we're using multiple different methods for displaying `.md` content, we use `markdownlint` to be sure it will render as intended. It would be great if gd2md could, at least by default, conform to conventions to maximize compatibility.

**Comment by evbacher** [comment]
Is there a problem rendering the converted Markdown? If so, please file a bug for that issue.

If I have time someday (!), I might try to write a formatter that would prettify the Markdown output, but that may not happen soon (and I suspect there are many competing standards for formatting!).

**Comment by galligan** [comment]
Understood and thanks @evbacher. Closing for now.
