### ISSUE TITLE
There is no "convert" option when trying to convert doc to Markdown. 

### ISSUE THREAD

**Issue by Sukanya-rs** [evbacher/gd2md-html#109]
Hi, 

I am trying to convert 'Google Document' to 'Markdown'. It does not give me "convert" option to as per the instructions. Please help!  

![Add-on->Docs to Markdown-> Help](https://user-images.githubusercontent.com/78011093/169831520-c1697c95-df6a-4c67-8176-20b3bb5a1e21.png)
![Issue](https://user-images.githubusercontent.com/78011093/169831533-f5f92450-8872-4b12-a7da-67e6e6480528.png)

Best regards,
Sukanya

**Comment by evbacher** [comment]
Thanks for filing this bug: It looks like the add-on was installed, but the convert menu item is not appearing. Can you try uninstalling and reinstalling and see if it behaves properly? Let me know with a comment what happens.

Also, Google has changed the top-level menu item from Add-Ons to Extensions. I'll change that in the docs.
