### ISSUE TITLE
Master code missing reckless mode changes?

### ISSUE THREAD

**Issue by CHHUM** [evbacher/gd2md-html#110]
I just downloaded the latest source from master as I want to try and make a couple of modifications but I seem to be missing the reckless mode update from the latest version of the addin.  

My version of the sidebar HTML has:
Demote headings (H1 → H2, etc.) 
HTML headings/IDs 
Wrap HTML 
Render HTML tags 
Suppress top comment 

VS. the version I'm running from the marketplace has:
 Demote headings (H1 → H2, etc.) 
  Use HTML headings/IDs 
  Wrap HTML 
  Render HTML tags 
  Suppress info comment 
  Use reckless mode (no alerts) 

Am I somehow picking up an older version or did the last changes not make it into master?

**Comment by evbacher** [comment]
Latest version (34) now in repo.
