### ISSUE TITLE
Issues formatting a large (legal) document

### ISSUE THREAD

**Issue by nbouvrette** [evbacher/gd2md-html#112]
Source document: https://docs.google.com/document/d/15zDjqbJ7B9KBthDEYl_LH_G-Anf9CRebvKWcU5RMyB4/edit?usp=sharing
Issues found:

- Header with numbers (bullets) are converted to number lists and we can't know they are headers anymore

<img width="1206" alt="image" src="https://user-images.githubusercontent.com/6453322/185725191-045eeee9-075a-42c6-8f99-a0a1c80bcdd2.png">

> Adding the number in the header could also be fine (e.g., `## 3. Overview`)

- In some cases where multiple levels of indentation occur, the formatter "get lost"

<img width="1215" alt="image" src="https://user-images.githubusercontent.com/6453322/185725226-9ff587ed-fa31-450b-b4e9-6b10b8fcca79.png">

Unfortunately because of the issues, we cannot use Docs to Markdown, so we have a baseline of the type of output we would expect using .docx to markdown [online converter](https://products.aspose.app/words/conversion/docx-to-md).

Here is the full output we use from the other tool: [termsOfUse.fr-CA.md](https://github.com/evbacher/gd2md-html/files/9386047/termsOfUse.fr-CA.md)

**Comment by evbacher** [comment]
The headers in your document _are_ numbered lists (as well as Heading 2). I suppose we could do some custom work to support this, but seems like a special case. Closing for now.
