### ISSUE TITLE
NetworkError: Connection failure due to HTTP 500

### ISSUE THREAD

**Issue by sijoyss** [evbacher/gd2md-html#115]
Can you please fix it?
Thanks

**Comment by evbacher** [comment]
Can you reproduce this? 500 is a generic server problem that is most likely on Google's side.

If you can reproduce with a particular document, please share with me (view access is sufficient).

**Comment by sijoyss** [comment]
You are right it was from google the issue was fixed after 10mins.
Regards

**Comment by evbacher** [comment]
Thanks -- closing this one.
