### ISSUE TITLE
Feature Request: Option to represent italic with single asterisks

### ISSUE THREAD

**Issue by a2k-hanlon** [evbacher/gd2md-html#117]
Thanks for developing this great extension and making it open source!

It would be convenient for the tool to to offer an option to have italic format represented in Markdown output as text enclosed in single asterisks (eg. *italic text* becomes `*italic text*`) instead of underscores (eg. _italic text_ becomes `_italic text_`), which are used currently.

This "italic format" option would also represent text that is both bold and italicized using triple asterisks instead of nested double asterisks and single underscores (eg. ***really important text*** becomes `***really important text***` instead of **_really important text_** becoming `**_really important text_**`).

**Use Case:** I have a markdown application (wiki.js) configured to render underscore-enclosed text as underlined instead of italic. I know this underlining behaviour is not standard markdown, but single asterisks for italic is standard markdown, and it would be very helpful to have this option.

**Comment by a2k-hanlon** [comment]
Another problem with using underscores for italic rather than asterisks is that underscores do not work for italicizing portions of words, whereas asterisks do. There's a note about this in _The Markdown Guide_: https://www.markdownguide.org/basic-syntax/#italic-best-practices

For example...

This works: `"It's levi*o*sa not levio*sa*"` > "It's levi*o*sa not levio*sa*"

This doesn't work:`"It's levi_o_sa not levio_sa_"` > "It's levi_o_sa not levio_sa_"

This presents another use case for the suggested option. Also, it makes me consider whether the default should be asterisks (perhaps the more robust option) or underscores (the existing behaviour). I'll leave that up to the maintainer(s) to decide though!

**Comment by a2k-hanlon** [comment]
This configurability could also potentially be extended to bold formatting (double underscores or double asterisks); however, just the change for italic format is suffice for the 2 use cases I shared above.

**Comment by evbacher** [comment]
*/** now the default for italic/bold markup in Markdown.
