### ISSUE TITLE
Error in Chrome - drive.google.com refused to connect.

### ISSUE THREAD

**Issue by JayHoltslander** [evbacher/gd2md-html#125]
Conversion window displays Chrome error screen:

>drive.google.com refused to connect.

Safari displays no error and conversion pane is empty.

**Comment by evbacher** [comment]
Probably this issue:
See https://github.com/evbacher/gd2md-html/wiki#drivegooglecom-refused-to-connect

**Comment by JayHoltslander** [comment]
Confirming that was indeed the issue. 
Logged out of all Google account. 
Logged in as single account. 
Extension functioned as expected. 

Thank you!
