### ISSUE TITLE
drive.google.com refused to connect

### ISSUE THREAD

**Issue by ladyblackk** [evbacher/gd2md-html#126]
trying to convert document to html I get this error
"drive.google.com refused to connect."
![image](https://github.com/evbacher/gd2md-html/assets/134188262/3b0dfe77-d5af-4721-a18c-1c1d1fa6bbda)

**Comment by evbacher** [comment]
Probably this: https://github.com/evbacher/gd2md-html/wiki#drivegooglecom-refused-to-connect

But if not, please reopen this issue.
