### ISSUE TITLE
Suggestion : Completely remove warning/conversion result from output

### ISSUE THREAD

**Issue by OshidaBCF** [evbacher/gd2md-html#128]
It's a bit annoying to every time have the `<!-- Yay, no errors, warnings, or alerts! -->` bit when copying, and if you actually copy from the output window you also get the `<!-- Output copied to clipboard! -->`

Could it be possible to just straight up remove them if there is no problem ?

Other than that, that addon is saving my fricking life, so thumbs up from me.

**Comment by OshidaBCF** [comment]
well i guess that because the info is in "comments" tag, pasting it somewhere would not render it, as it is a "comment"

But that's usually not the case because most text editors like reddit just interpret this as text

**Comment by evbacher** [comment]
Yes, this makes a lot of sense. I'll try to remove that and update the checkbox description to "Suppress info comments." when I get a chance. Thanks for the suggestion.

**Comment by evbacher** [comment]
Update to remove unnecessary output in 1.0B35 (currently the live version). If you do have errors or alerts, there will be an error comment, even if you suppress all the info comments. And note that reckless mode suppresses the inline alerts, but not the error comment at the top.

**Comment by OshidaBCF** [comment]
this is perfect
![image](https://github.com/evbacher/gd2md-html/assets/61458287/f3b90877-d256-4682-b636-2555ff48e3ee)

this is an added space just before it but that's not a big problem

thks a lot

**Comment by OshidaBCF** [comment]
it was working perfectly this morning and now this appeared
![image](https://github.com/evbacher/gd2md-html/assets/61458287/cc343e16-00d5-4120-855e-b530ea101567)

**Comment by evbacher** [comment]
That is by design. If for some reason, the copy-to-clipboard fails, it will show this comment. Let me know if this keeps happening -- hopefully it's a rare and intermittent problem.

**Comment by OshidaBCF** [comment]
Ahhhh i see.

It fail if my mouse isn't focused on chrome, which make some sense.

So no problem.

**Comment by evbacher** [comment]
Oh, that is very interesting. My guess is that when the focus is in another tab, the clipboard "belongs" to the other tab, so the add-on cannot write to it. Thanks for enlightening us!

**Comment by OshidaBCF** [comment]
It's not really a problem tbh, i usually press "markdown" then switch on discord to reply to a message

plus i got used to selecting the "part" i needed so it's not really a problem.
