### ISSUE TITLE
ScriptError: Authorization is required to perform that action.

### ISSUE THREAD

**Issue by RhythmLunatic** [evbacher/gd2md-html#13]
That's what I get when I try using the addon

**Comment by evbacher** [comment]
Do you get an authorization dialog? The add-on requires permission to access the current Doc and to display the sidebar.

**Comment by RhythmLunatic** [comment]
I'm not sure? It asked for authorization when I installed the script, but this is what it says in the sidebar.

Regardless I ended up using a different utility so the issue is moot

**Comment by JohanHanssonPub** [comment]
I'm also experience this issue. I.e. there is no authorization dialog showing at any stage of the flow. When is it supposed to occur?

**Comment by KikeVen** [comment]
ScriptError: Authorization is required to perform that action.

**Comment by evbacher** [comment]
Sorry you've had a problem. Can you describe what happened? Did you get this error when you try to run the add-on.

If you remove the add-on and install it again, do you still have the problem?

**Comment by KikeVen** [comment]
Thank you for your quick response. I did remove it and installed it again, but it didn't work. This afternoon I made a change to that google account. I activated two step authentication.

I tried the extension in another google account, and it worked fine. The only difference is, I don't have two step auth in the one that worked.

Thanks again

**Comment by JayHoltslander** [comment]
I'm having this problem too. I installed the add-on the other day. Authenticated it. Tested it. It worked. Today though I get the error.

**Comment by JayHoltslander** [comment]
Update. Error was received in Safari. Tried again in Chrome. It worked.

**Comment by Merith-TK** [comment]
still getting this error

**Comment by evbacher** [comment]
If you get this error again, please file a bug and share a (view-only) copy of a Doc that causes the error so we can check it out.
