### ISSUE TITLE
TOC not working

### ISSUE THREAD

**Issue by wendeavontuur** [evbacher/gd2md-html#132]
I have a working toc in my Google Document. When I place links to these headings in my google document they correctly send me to the right headings. However when I render the document to HTML (and use the 'Use HTML Headings/IDs') I get errors. 

> undefined internal link to this URL: "#heading=h.y0b8p6b0ylvv".link text: ....
> ?Did you generate a TOC with blue links?

**Comment by evbacher** [comment]
Can you share a doc that shows this behavior?

Note: if you don't generate the TOC with the blue links, Docs to Markdown cannot pick up the link IDs. I don't believe the Use HTML Headings/IDs option makes any difference.
