### ISSUE TITLE
extension not working

### ISSUE THREAD

**Issue by rajganguly96** [evbacher/gd2md-html#133]
The extension is not working. it is not launching in the doc.

I went to extensions menu > docs to markdown and there is only 'help' option available nothing else.

**Comment by evbacher** [comment]
Sorry this is not working for you. What happens when you click Help? It seems like it may be an installation problem. Can you remove it and reinstall?

**Comment by jarkman** [comment]
I had the4 same issue, removed and reinstalled, and I then saw the Convert menu item. Worked great, thanks.

**Comment by evbacher** [comment]
I am going to add a note about this in the troubleshooting section. I'm not sure why installation is incomplete sometimes, but that is outside the scope of the extension itself. Thanks for your notes on this issue though.

**Comment by jarkman** [comment]
I do think I installed it two different ways - 

the first time by googling then landing on https://workspace.google.com/marketplace/app/docs_to_markdown/700168918607, 

the second from the Extensions menu in a document.

Not sure if this is at all relevant to the problem.

**Comment by evbacher** [comment]
I think that both ways lead to the same URL. In any case, I added a [troubleshooting note](https://github.com/evbacher/gd2md-html/wiki#installation-issues).
