### ISSUE TITLE
Cannot install this plugin at all via Google Extensions (error 400)

### ISSUE THREAD

**Issue by costacoz** [evbacher/gd2md-html#135]
When I click "Install" it opens dialog window and I get:
> Bad Request
> Error 400

**Comment by evbacher** [comment]
That 400 response is coming from Google's servers, not from the extension. The best advice I can give you is to try again later.

**Comment by costacoz** [comment]
@evbacher I'm sorry! It's on my side.

**Comment by evbacher** [comment]
No worries -- it may be an intermittent Google server issue as well. I did add a [troubleshooting note](https://github.com/evbacher/gd2md-html/wiki#installation-issues).
