### ISSUE TITLE
Privacy policy link is broken

### ISSUE THREAD

**Issue by jrahal-mx** [evbacher/gd2md-html#136]
The privacy policy link in the Readme and the Google Marketplace page goes to a "Site not found" error. Is there somewhere I can find the privacy policy for this addon? Thanks!

**Comment by jrahal-mx** [comment]
Readme now points to theprivacy policy page in the repo wiki. 

https://github.com/evbacher/gd2md-html/wiki/Privacy-policy#docs-to-markdown-privacy-policy

**Comment by evbacher** [comment]
Now at https://beanroad.com/docs-to-markdown/privacy.html
