### ISSUE TITLE
Doesn't show the actual conversion action anymore

### ISSUE THREAD

**Issue by hakanai** [evbacher/gd2md-html#138]
The only action provided by the plugin now is Help, which says to use the Convert action, but Convert is nowhere in the menu.
This makes it impossible to use the plugin at all.

![image](https://github.com/evbacher/gd2md-html/assets/43236/385750b9-a9e0-467c-bb32-8a441b75fade)

**Comment by evbacher** [comment]
See https://github.com/evbacher/gd2md-html/wiki#troubleshooting, specifically this bit:

Missing menu items: If you installed the add-on, but you see only the Help menu, try uninstalling the add-on, then reinstalling it. You should see both the Convert and Help menus.

**Comment by hakanai** [comment]
True enough, it seemed to install properly on the second try. (Chrome issue?)
