### ISSUE TITLE
bug: Installed extension to workspace, checked admin, all permissions are granted, but does not show up in google doc extension menu

### ISSUE THREAD

**Issue by pklecha** [evbacher/gd2md-html#144]
is there anything extra that I need to do or is the installation flawed?

**Comment by evbacher** [comment]
See https://github.com/evbacher/gd2md-html/wiki#installation-issues. Occasionally, the menu items do not show up, but in your case, does the Docs to Markdown add-on not show up at all in the Extensions menu?

In any case, I recommend uninstalling and try installing again. Let me know what happens.

**Comment by evbacher** [comment]
Any luck?

**Comment by evbacher** [comment]
Closing this for now -- if you still have this problem, please reopen.
