### ISSUE TITLE
Addon cannot copy to clipboard on firefox

### ISSUE THREAD

**Issue by OshidaBCF** [evbacher/gd2md-html#146]
Weirdly enough the extenssion cannot copy to the clipboard. it just doesn't work automatically

**Comment by evbacher** [comment]
I tried this with Firefox and it did copy to the clipboard (I'm on a Macbook). Note that the add-on doesn't report that it copied to the clipboard (if successful).

**Comment by OshidaBCF** [comment]
It actually works half the time, i think if i "select" some of the text that's written during generation it works

**Comment by evbacher** [comment]
Do you see this at the top of your converted output if the copy to clipboard fails?

`<!-- Copy and paste the converted output. -->`

**Comment by OshidaBCF** [comment]
when i see this line it doesn't copy to clipboard

**Comment by evbacher** [comment]
One way that this can happen (for a conversion that takes several seconds) is that if you go to another tab while you're waiting, the tab where the conversion is taking place doesn't own the clipboard anymore, so it can't copy to the clipboard.

See https://github.com/evbacher/gd2md-html/wiki#output-not-copied-to-the-clipboard
