### ISSUE TITLE
Issue: conversion adds watermark at bottom of converted text

### ISSUE THREAD

**Issue by dkwonkhe** [evbacher/gd2md-html#147]
When converting a gdoc to HTML GD2MD now adds a short "watermark" to the end of the code. If not deleted this breaks stylesheets. There does not appear to be an option to not include it, current workaround is to manually delete before use.

Ideally it would be great to remove this "feature" entirely, but if not a check box to turn it off would be appreciated.

**Comment by OshidaBCF** [comment]
indeed it's pretty annoying

**Comment by evbacher** [comment]
Removed.
