### ISSUE TITLE
Where is the original google doc

### ISSUE THREAD

**Issue by mdarfler** [evbacher/gd2md-html#16]
Hello,

I really love working with your Add-on but I don't where the original google doc is so that I can use that as a reference. when i click on the link https://github.com/evbacher/gd2md-html/wiki/Demo-and-sample-doc it just redirects back to the wiki.

**Comment by evbacher** [comment]
Good point. I've shared the Docs publicly now (both the main page and the demo doc). So you can try converting the original Docs and see how it works. If you go to https://github.com/evbacher/gd2md-html/wiki/Demo-(Markdown-conversion), there's a link to the original doc at the top (after the alerts).

**Comment by evbacher** [comment]
Let me know if the shared Doc is not working for you.
