### ISSUE TITLE
Google Doc's new Document Tabs feature has broken links to headings

### ISSUE THREAD

**Issue by ShokoTB** [evbacher/gd2md-html#172]
After Google rolled out its new Document tabs feature in Google Docs, Docs to Markdown is now unable to resolve links to headings. I realize that this is outside of your control but would really appreciate having Docs to Markdown working again. Thank you.

**Comment by evbacher** [comment]
I'm happy to report that internal links are now working as before. Fix was a bit tricky, but it should be OK now, regardless of which tab you're converting from. Please open a new bug if you see any issues I've missed relating to this.

Note: If you have duplicate headings (headings that contain exactly the same text), internal links to the second (or third) duplicate headings will go to the first heading. Duplicate headings are not a good practice, but we can fix this. I'm opening a new bug, but may not get to that for a bit after some other development work.

**Comment by ShokoTB** [comment]
Wonderful news! Thanks so much!

**Comment by evbacher** [comment]
You're welcome -- thanks for filing the bug! If you notice anything unusual, please reopen this bug.
