### ISSUE TITLE
Markdown for newlines

### ISSUE THREAD

**Issue by microcosm** [evbacher/gd2md-html#18]
Related but different to the [other issue I raised](https://github.com/evbacher/gd2md-html/issues/17).

When the gDoc contains a newline (via SHIFT+ENTER, as opposed to a paragraph break), markdown can mark that up [using double-space at the end of the line](https://markdown-guide.readthedocs.io/en/latest/basics.html#line-return). However that functionality appears to be absent from this addon.

**Comment by evbacher** [comment]
If we could detect the shift-enter, we could use a \ line termination.

As I mentioned on the other bug, unfortunately, there's no way to detect a shift-enter line break in a Doc from Apps Script (that I'm aware of). The bold text renders properly, but without the line break. See https://github.com/evbacher/gd2md-html/wiki/Markdown-playground#formatted-text-and-soft-line-breaks for a test.

It might be possible to detect line-break characters (\r), but that might be expensive. If I have a chance, I'll check it out.

**Comment by evbacher** [comment]
Never mind. We can do this. I'll get it in when I get a chance.

**Comment by microcosm** [comment]
Oh, that's great! I'm glad you found a way!

**Comment by evbacher** [comment]
Fixed in v 1.0β10. Please reopen (or open another bug) if still a problem.
