### ISSUE TITLE
How to specify target in generated href

### ISSUE THREAD

**Issue by philixxx** [evbacher/gd2md-html#23]
Is it possible to specify target="_blank" in generated href ?

**Comment by evbacher** [comment]
It would be possible to add that to generated links, but I'm loathe to add too many options or departures from what's directly in the Google Doc content. This would be easy enough to add after conversion via a Perl or Python script.

**Comment by evbacher** [comment]
Closing for now -- this is a non-obvious side-effect of conversion, and not everyone wants that behavior.
