### ISSUE TITLE
Plaintext < and > are not exchanged for &lt; and &gt;

### ISSUE THREAD

**Issue by Pinaz9** [evbacher/gd2md-html#24]
I write with the angle brackets a lot, and if these character are not escaped, this addon is nearly unusable, as any text between angled brackets are counted as code and not displayed.

**Comment by evbacher** [comment]
Thanks for this bug -- I'm surprised it has not come up before. I'll make this change as soon as I get a chance.

**Comment by evbacher** [comment]
I do know of some users who add HTML tags specific to their targets, so this change would break them, but I think in general that escaping < (and maybe >) is the right thing to do.

**Comment by Pinaz9** [comment]
Thank you very much for your consideration on this matter. This will make it even easier to ditch Word for good!

**Comment by evbacher** [comment]
Just curious -- how do you convert from Word to Markdown or HTML?

**Comment by Pinaz9** [comment]
Word allows you to save to several types of HTML (and really makes a mess out of it each time), and I just wrote a python script for Notepad++ that cleaned it up the rest of the way. With regex, the process can be adapted to Markdown as well, though I don't think it would be worth the effort.

**Comment by evbacher** [comment]
I've added a new option to GD2md-html. By default, it now replaces < with &lt;. This should solve your problem. But selecting the Allow HTML tags option will allow <tag> to appear as-is. Or, you can use the default setting and type \<tag> in the Doc. Reopen if this does not work properly.

**Comment by Pinaz9** [comment]
Woot! Thanks, dude!

**Comment by evbacher** [comment]
You're welcome! I think we have the best of both worlds now (I hope).

**Comment by Pinaz9** [comment]
Bad news. Either the new version isn't up yet, or something went wrong. It's not parsing `<` and `>`.

**Comment by evbacher** [comment]
Hmm. Did you reload the Doc? Can you check the version number in the top comment? It should say:

* GD2md-html version 1.0β12

When the new option is NOT selected, it should replace < with &lt;, which is what you want, I think.

**Comment by Pinaz9** [comment]
I actually only reinstalled the addon this morning, and checking just now, it is indeed GD2md-html version 1.0β12.
Do you mean to say it replaces < with &amp;lt;?

**Comment by evbacher** [comment]
Yes, the default behavior is changed now: by default, will replace < with &amp;lt;

If you really want to preserve the HTML tags (which a few people actually want to do), select the option and < will NOT be replaced with &amp;lt; (sorry -- forgot that the entity would show up as < here!).

**Comment by Pinaz9** [comment]
Did you use some sort of compiler? If it might have decided to be helpful and render the entity before compiling to vanilla JS. In any case, 1.0β12 is not performing as described. The state of the checkbox has no appreciable effect on the output for the input `<This is not a tag.>`

**Comment by Pinaz9** [comment]
You may want to consider using [String.raw](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/raw) to keep things from interpreting the entity.

**Comment by Pinaz9** [comment]
If you would consider putting the source code on here, I'd be willing to lend you a second pair of eyes.

**Comment by evbacher** [comment]
I am planning on open-sourcing this -- would be great to have more eyes on this code -- thanks! I need to go through some paperwork and put together some contributor guidelines, but I will get to it sometime soon. Cheers.

**Comment by evbacher** [comment]
I have a simple version of this working now. Needs some more testing before I release it.

Behavior is:
* Replace < with &amp;lt; everywhere, unless escaped (\<) in case you really want an HTML tag.

**Comment by Pinaz9** [comment]
Having finally gotten some time to test this, I find that I have no idea how to get the code to test it with. It is certainly not deployed yet, or at least it doesn't seem to be.

**Comment by evbacher** [comment]
I have not had the time to get back to this. The fix should be simple -- I will try again soon if possible.

**Comment by evbacher** [comment]
Sorry for the delay: Publishing via G Suite Marketplace added some complexity, but I think I've finally figured it out.

I've made this change to escape HTML tags by default. There's an option to render them if you want.

Please let me know if you have any problems with this, otherwise, I will mark this (and the duplicate fixed).
