### ISSUE TITLE
TypeError: Cannot find function getSelection in object

### ISSUE THREAD

**Issue by AntonMuratov** [evbacher/gd2md-html#25]
TypeError: Cannot find function getSelection in object ERROR opening active document: Exception: The action is not allowed.

**Comment by evbacher** [comment]
Thanks for the bug. Were you making a partial selection? Is it possible to share the doc with me so I can reproduce?

**Comment by AntonMuratov** [comment]
Yes, shure!
https://docs.google.com/document/d/1qiWT9SRnyePP_0tt80t1Y4FiCLdrjQ9F-rHNUAb9hzI/edit

**Comment by AntonMuratov** [comment]
the bug is fixed, thanks!

**Comment by evbacher** [comment]
Heh -- I could not reproduce, so was not able to change anything. Must have been a momentary glitch with Drive. Glad it's working for you though.
