### ISSUE TITLE
GD2md-html not displayed in Add-ons menu

### ISSUE THREAD

**Issue by aselivanava** [evbacher/gd2md-html#26]
GD2md-html is not displayed in the Add-ons menu of Google Docs. I've tried reinstalling the add-on, bu there was no success.

**Comment by evbacher** [comment]
Does it report any kind of error message? Let me know if this is still happening for you.

**Comment by aselivanava** [comment]
There is no error at all - the app is not displayed in the Add-ons menu. I am using Chrome 66.

However, everything is OK in Mozilla.

**Comment by evbacher** [comment]
I'm glad you can at least use it in Mozilla. I'm running Chrome version 67 right now.

Another question: if you open a Doc in an incognito window with no Chrome extensions, does it work then?

**Comment by evbacher** [comment]
Closing this for now -- please reopen if this is still a problem in Chrome.
