### ISSUE TITLE
Option to use Github markdown style

### ISSUE THREAD

**Issue by tamalsaha** [evbacher/gd2md-html#27]
This chrome extension is really handy. Can you support a `[ ] GitHub Markdown` so that Github friendly markdown is generated?

**Comment by evbacher** [comment]
Hi Tamal,
I'm actually not that familiar with Github Markdown, though the main wiki page here is converted directly from a Google Doc and it required minimal changes.

What specific features are you looking for? I know that Github Markdown does not support footnotes or definition lists. What else is missing? I'd be happy to consider adding an option if it's not too difficult to implement.

**Comment by evbacher** [comment]
Please reopen if you have specific Github Markdown things you'd like to support/
