### ISSUE TITLE
Convert strikethrough text

### ISSUE THREAD

**Issue by evbacher** [evbacher/gd2md-html#29]
Convert strikethrough text in a Doc to \~\~strikethrough\~\~ in Markdown and \<del>strikethrough\</del> in HTML.

**Comment by tjose07** [comment]
This would be great. Right now the add-on seems to miss this –converting strikethrough text to HTML–.

Thanks!

**Comment by tjose07** [comment]
This is great news. Thanks for a great and useful app

**Comment by evbacher** [comment]
Strikethough text seems to be operating properly as of today's new version. Please reopen this bug if not.
