### ISSUE TITLE
Can h1 etc not include full length bold

### ISSUE THREAD

**Issue by indiamcq** [evbacher/gd2md-html#31]
Just because the 
h1 **is bold**
I want it to come out like this:
`# is bold` 
not like this:
`# **is bold**`
If I want good Markdown then I do not want the whole of the text in any header to have bold markup. I want my final process to do that if needed.
Can there be an option to strip the bold off headers?

**Comment by evbacher** [comment]
You may have explicitly styled a heading as bold using the B button. In general, GD2md-html only adds bold, italic, etc. if it's been added explicitly in the Doc. For example, this is a conversion of a doc that has one standard h2 and one that's been selected and bolded:

# gd2md-html demo/test doc


## Standard H2 (style is not bold)

some text


## **H2 explicitly bold (using B button)**

some more text

**Comment by indiamcq** [comment]
I understand it is behaving as expected. I'd just like an option to remove bolding or italic or underline when all the text is styled that way in a header. I don't know how to make this a feature request.
The main reason to go to Markdown is to get rid of hidden junk and have simplified markup. 
In this case it is making the junk visible. So that is good.
I appreciate this neat tool and writing the text in the sidebar.
I don't need a reply.

**Comment by evbacher** [comment]
I'm going to close this for now. There are many ways to abuse formatting in Google Docs and other word processors. Docs to Markdown cannot anticipate all of them (not easily at least).
