### ISSUE TITLE
Name and discoverability

### ISSUE THREAD

**Issue by miohtama** [evbacher/gd2md-html#32]
This is a good add-on, but I the name "gd2md" makes is hard to find it.

I suggest you rename the addon something like "Docs Markdown Export" or similar within the domain of human languages :)

**Comment by evbacher** [comment]
Not a bad idea. gd2md-html is very literal but not very readable. Maybe "Docs export to Markdown/HTML", which is a bit more readable (and searchable)?

**Comment by liamhardygtf** [comment]
Hi @evbacher 
I'm trying to whitelist this add-on for our organisation's Gsuite users. However, when I use the "Add apps to the whitelist" function, and search, I can't find this add-on at all. 
I'm definitely searching for the right characters. 
I don't want to stop our users accessing this add-on, but we need to restrict to only whitelisted add-ons. Any ideas?

**Comment by evbacher** [comment]
Now available in the G Suite Marketplace: https://gsuite.google.com/marketplace/app/docs_to_markdown/700168918607

Renamed to "Docs to Markdown" for a bit more clarity.

Let me know if this works for you (or not).

**Comment by liamhardygtf** [comment]
Many thanks Ed. It is now visible in the search and I have whitelisted it for our organisation. Thanks for your help!
