### ISSUE TITLE
Nested lists do not close

### ISSUE THREAD

**Issue by kinstaadmin** [evbacher/gd2md-html#34]
This one is possible related to #3. This issue isn't with list item closures but with closing nested list containers `ul` and `ol`. This leads to a behavior where onece yo have a nested list, the list never returns to the original level: 

![image](https://user-images.githubusercontent.com/41046498/51182702-4cf60800-18cf-11e9-802b-9f3dd9929e62.png)
This image shows the original doc, note that “Security Event” returns to the previous level.

![image](https://user-images.githubusercontent.com/41046498/51182724-5aab8d80-18cf-11e9-9810-560c4cc4c713.png)
This is the HTML with the unclosed sub-list. The “Security Event” just continues on as there is no closing list element.

**Comment by kenrussell** [comment]
Could this bug please be prioritized? Markdown lists are generated with good fidelity, but not HTML lists. Thanks.

(Alternatively, I'm happy to try to fix it - is the source code for gd2md-html available somewhere?)

**Comment by evbacher** [comment]
Latest version (1.0β16) updated Feb. 28, 2019 supports simple nested lists properly in HTML.  See https://github.com/evbacher/gd2md-html/wiki/Demo-(HTML-conversion)#lists for an example HTML conversion.

For nested list items that include paragraphs or codeblocks, we still have a problem. I will open another bug for that.

**Comment by kenrussell** [comment]
Thank you for the fix!
