### ISSUE TITLE
Front Matter

### ISSUE THREAD

**Issue by luckyluke007** [evbacher/gd2md-html#35]
I tried to do a front matter for Jekyll site on top of Google doc, but when I exported it, the "---" removed from Markdown.  Any idea, how to keep the "---"?

**Comment by evbacher** [comment]
Do you mean that something like this in a Google Doc doesn't get converted?

---
layout: post
title: Blogging Like a Hacker
---

The "---" represents a horizontal line in Markdown -- that's what I'm seeing after conversion, though each line becomes a separate paragraph:

---

layout: post

title: Blogging Like a Hacker

---

**Comment by luckyluke007** [comment]
Okay.
I am looking to save those for Jekyll site.

**Comment by evbacher** [comment]
I'm going to close this issue, since we are just converting the Google Docs text so that it renders as close to the original as possible in Markdown or HTML.
