### ISSUE TITLE
numbered lists do not increment

### ISSUE THREAD

**Issue by paragbaxi** [evbacher/gd2md-html#36]
```
1. blah 1
2. blah 2
3. blah 3
```
gets converted to:

```
1. blah 1
1. blah 2
1. blah 3
```

**Comment by evbacher** [comment]
You're right.

While using 1. for all ordered list items is legal Markdown and convenient if you have long lists that you're creating by hand, there's no reason for a converter to do the same. This should (I hope) be an easy change to make.

**Comment by evbacher** [comment]
The latest version (published today) increments ordered list item numbers properly. Please reopen this bug (or open another) if you see any issues related to this change.
