### ISSUE TITLE
Support: Where is the source code?

### ISSUE THREAD

**Issue by patcon** [evbacher/gd2md-html#37]
Hi! Thanks so much for this tool! I'm hoping to script similar functionality, and was curious whether the source code existed anywhere, or if it was private :)

**Comment by evbacher** [comment]
I'm so glad you like this tool -- thanks for your interest! Currently private, but I am in the process of going through the release process to make this open-source, write some contributor guidelines, etc.

**Comment by patcon** [comment]
Ah gotcha! Thanks for considering, Ed!

**Comment by gewentao** [comment]
Hi @evbacher , thanks for the amazing tool. Is there any updates about the open source process?

**Comment by evbacher** [comment]
Hi @gewentao. I suspect this is the lament of many side-project maintainers, but my day job is keeping me very busy. I will try to find the time to get open-source approvals and post the source here. Do you have enhancements in mind?

**Comment by jeshan** [comment]
Personally, I'd want it open source for privacy concerns and deploying it myself

**Comment by theprojectsomething** [comment]
Agree with @jeshan on privacy concerns, also for issue resolution :)

**Comment by georgebrindeiro** [comment]
I'd like to be able to add other Markdown flavors. We use Contentful where I work and it supposedly follows the Github-flavored Markdown specification... But right now things aren't translating perfectly for my team.

**Comment by dwalks12** [comment]
This is a solution that works:
https://github.com/dwalks12/googledoc-to-md-to-html

Converts doc to markdown then markdown to html using showdownjs.

**Comment by evbacher** [comment]
Source code is available now in the addon/ directory. Enjoy!
