### ISSUE TITLE
Smart quotes get turned into straight quotes

### ISSUE THREAD

**Issue by jeremyzilar** [evbacher/gd2md-html#38]
As editors of an arts publication, we often use “smart” quotes in our articles.
However, when we use `gd2md-html`, the smart quotes all get turned into "straight quotes".

would be great if they were also replaced with `&#8220;` and `&#8221;`

Is there anyway this could be added in as a setting or option? Or are there ways in which we can extend the functionality of this add-on?

**Comment by evbacher** [comment]
Thanks for this, Jeremy.

The original use for this converter was for developer documentation, where smart quotes cause problems with any sample code. One thing we could do is convert all quotes in code blocks or code font runs to straight quotes, but leave all the other ones alone. I'm trying to keep the options at a minimum. I will investigate this.

**Comment by jeremyzilar** [comment]
Thanks for looking into this @evbacher !

**Comment by evbacher** [comment]
New behavior:
Smart quotes in code and code blocks will convert to straight quotes. Smart quotes in other text will be preserved.

Please reopen this bug if you see any cases where this is not true.

**Comment by jeremyzilar** [comment]
THANK YOU @evbacher 🎉 You are amazing
