### ISSUE TITLE
Adds unwanted line breaks to html output

### ISSUE THREAD

**Issue by s8m2s** [evbacher/gd2md-html#4]
HTML output seems to add line breaks to the output code. Not <br> tags, but actual line endings. While whitespace is ignored by html, when pasting into wordpress, the new lines are turned into line breaks which affects the flow of text.

**Comment by evbacher** [comment]
We originally developed this to convert to Markdown (which is sensitive to whitespace). HTML renderers should be more forgiving. While this is probably a bug with Wordpress, I'll check it out when I get a chance.

**Comment by jtsternberg** [comment]
Yes, this is a result of the WordPress formatting. Line breaks are converted to either `<br>` or `<p>` tags. Was very excited about this extension for being able to export clean html for WordPress, but the line breaks are a deal breaker.

**Comment by evbacher** [comment]
If we take the view that we're just converting the content and marking it up with either Markdown or HTML, then perhaps the right thing to do is not to do any line wrapping. If folks really want to wrap HTML, they can use HTML Tidy for that.

**Comment by evbacher** [comment]
Planning to change to default no-wrap (and add an option to wrap HTML output). Will ping this bug and mark fixed when the fix is live.

**Comment by evbacher** [comment]
Fixed in v1.0β4. Default is now not to wrap HTML text, with option to wrap.

**Comment by evbacher** [comment]
fixed in v1.0β4.

**Comment by evbacher** [comment]
Sounds good. If you break it, don't forget to file a bug!
