### ISSUE TITLE
It is impossible to remove this app

### ISSUE THREAD

**Issue by jerzyjamroz** [evbacher/gd2md-html#40]

**Comment by evbacher** [comment]
Can you provide some details? Did you try to remove it from a Doc using Add-ons > Manage add-ons...?

**Comment by jerjam** [comment]
Yes,  Add-ons > Manage add-ons-> Manage -> Remove, it disappears, but once I open another document, it is back again. I tried to remove it few times without any result. Other apps do not have that issue.

**Comment by evbacher** [comment]
I am sorry this is a problem for you. This also happens for me on one account, but not on another. Do you recall if you installed Docs to Markdown from the Chrome Web Store (https://chrome.google.com/webstore/detail/docs-to-markdown/igffnbdfnodiaphfmfaiiaegmoljbghf) or from the G Suite Marketplace (https://gsuite.google.com/marketplace/app/docs_to_markdown/700168918607)?

In any case, I will raise an issue with the Drive add-on folks describing what's going on.

**Comment by evbacher** [comment]
The add-on might have been installed by your G Suite administrator, if you did not install it yourself. See https://support.google.com/a/answer/6208960?hl=en for information about finding out who your G Suite admin is.
