### ISSUE TITLE
Add option to remove link to document

### ISSUE THREAD

**Issue by egag21** [evbacher/gd2md-html#41]
If the comments include a link to the Google doc then there's a chance someone will use it to get to the document. I would like an option to hide information about the source of the document.

**Comment by bripmccann** [comment]
It's easy enough to just remove the URL, but yeah, an option to prevent the URL from being added in the first place could make things easier.

**Comment by egag21** [comment]
Yeah, it's easy to delete, but I'm dealing with hundreds of files so the chance for human error is high.

**Comment by evbacher** [comment]
I may provide an option to suppress errors and alerts, and I may remove the doc link altogether and just print the doc title in the comment. That way, the owner knows the name of the source doc, but the direct link won't be there for readers.

**Comment by evbacher** [comment]
Thanks for discovering and reporting this bug!

Latest version (Docs to Markdown 1.0β19) prints the doc title, but not the URL in the opening comment. That way, the author and editors can find the doc, but the URL is not exposed.
