### ISSUE TITLE
TypeError: Cannot find function getSelection in object ERROR opening active document: Exception: Action not allowed.

### ISSUE THREAD

**Issue by Elara-moon** [evbacher/gd2md-html#44]
When I first tried to use the add-on, I went to it and hit convert and the sidebar would open properly, but then when I tried to click either markdown or HTML, I got a 'ScriptError: Authorization is required to perform that action.' error. As far as I can tell, it does already have every permission I can give it, and I do not get any sort of authorization dialogue when I try it. I have already tried removing and re-adding it, as well.

![image](https://user-images.githubusercontent.com/51177140/58590549-ef34dd80-8229-11e9-8b80-8975e28a90fe.png)

^That's the error it gave

After that, I tried adding the add-on to my main/ default google account, the one my chrome is synced to. When on google docs on that account, I can use the add-on without any issues; I also tried using it on my other account in a document that both accounts had access to and it worked fine. However, if I try to use it in a google doc that my main account doesn't have access to, I instead get a different error: 'TypeError: Cannot find function getSelection in object ERROR opening active document: Exception: Action not allowed.'

![image](https://user-images.githubusercontent.com/51177140/58591316-9d8d5280-822b-11e9-9d8c-dde485f60ebb.png)

It works fine if I add my main google account to the doc, but I prefer to keep my accounts' documents separate, so it's a little bit annoying. (Otherwise it's great, though!)

Thanks.

**Comment by evbacher** [comment]
I'm sorry this is causing you trouble. The authentication model for add-ons is complicated, and I believe that what you describe is consistent with the need to be signed in as the same user who installed the add-on.

There's more information about the gory details here: https://developers.google.com/gsuite/add-ons/concepts/editor-auth-lifecycle, but I'm not sure that really clears up the picture.

Docs to Markdown is not doing anything fancy with authentication, and I think we're generally following the recommendations described in that web page. I'll add more here if I find some better information.

**Comment by Elara-moon** [comment]
Okay. I'll just deal with it, then -- it's still way better than re-formatting everything. Thanks for the response.

**Comment by evbacher** [comment]
One thing I've done with two different accounts is to open an incognito browser window and sign in there with my other account (open a GMail tab). Then install the add-on for that account there. I think you need to have the add-on installed for each different account.

**Comment by Elara-moon** [comment]
Oh, okay. It does work properly on an incognito browser. I didn't think of that. Thank you very much for the help!
