### ISSUE TITLE
Suppress error messages in document?

### ISSUE THREAD

**Issue by readtedium** [evbacher/gd2md-html#5]
Hey, thanks for making this—I'm glad to see a tool that converts Markdown without many errors around bold and italic characters, which I know was a sticking point of the old gdocs2md plugin. I just wanted to offer a couple of thoughts/ideas on this:

- **I think there should be a way to suppress error messages,** especially as they show up inline in some cases. (Some of the things that create error messages, specifically the message around there being multiple H1s in a document, aren't useful for me, as I tend to write multiple headlines when I'm editing.)  My suggestion would be to either put them all at the top of the document so they don't disrupt the flow of the doc, or to allow users to turn them off entirely. For my purposes (mostly just standard core features of the MD spec like links, headers, bold, ital, blockquote, and the occasional image), the error messages would probably just slow things down.
- **Since Google Docs doesn't have a natural equivalent to the blockquote,** I wonder if you'd be open to making it so that when a section is indented, it treats the indent the same as a blockquote. Could be left as an option for users.

Overall though, thanks for creating this. I write everything in Markdown, but all my stuff inevitably gets edited in Gdocs, meaning that it creates a lot of headaches around trying to convert things back. This helps ease some of the frustrations, I think. :)

**Comment by evbacher** [comment]
Hi -- glad you like gd2md-html for converting Google Docs to Markdown. This is a side project, so I'm not sure when I'll get to these, but thanks for the suggestions!

* **Suppressing error messages**: I'll consider this as an enhancement request, but if your Google
   is pretty clean, you shouldn't have any error messages. Usually, they're a warning that something won't render properly (or images that need to be handled separately. One exception is the multiple H1s: that's the convention we tend to observe at Google, but it's not technically an error.

*  **Blockquote**: Google Docs does allow you to indent a block, but there's nothing that marks it explicitly as a blockquote element. Processing indented paragraphs is certainly possible, but I'm not sure how complicated it would be. One workaround for now (and this is true for almost any Markdown element) is that you can just write a Markdown blockquote in your Doc.

**Comment by evbacher** [comment]
Regarding the H1 heading warning. I agree with you that that should not be an inline warning. I'll remove that when I get a chance (probably as a separate bug).

**Comment by shortformblog** [comment]
Thanks! Appreciate it.

**Comment by evbacher** [comment]
Closing this -- heading warning fixed, and there's another bug for the blockquote/indent issue that's still open.

**Comment by readtedium** [comment]
Thanks for taking care of this, by the way.

**Comment by evbacher** [comment]
You're welcome -- I'll try to think about the block quote/indent issue when I have some time.

**Comment by evbacher** [comment]
@readtedium Exploring the behavior of Google Docs might be a good subject for you newsletter!

**Comment by readtedium** [comment]
@evbacher I love that you suggested this. Let me think on it—I think it could be a lot of fun. Will keep you posted, cheers!
