### ISSUE TITLE
Block quotes?

### ISSUE THREAD

**Issue by Jessime** [evbacher/gd2md-html#51]
Hey, absolutely loving the add-on so far!

I was wondering if there's any formatting I can do in the google doc that will output a block quote in html?

Thanks!

**Comment by evbacher** [comment]
Sorry for the delay in responding to this.

I don't believe Google Docs has an attribute that denotes a block quote (other than an additional indent). The converter is looking at specific attributes -- it is not using whitespace as markup (like Markdown does).

Closing for now, unless you're aware of a way that Google Docs can explicitly signal a block quote.
