### ISSUE TITLE
Table contains backticks instead of <code> tags

### ISSUE THREAD

**Issue by pcimring** [evbacher/gd2md-html#52]
Hi

I am trying to convert the following table to markdown and HTML:

https://docs.google.com/document/d/1n4QRS9Rr8pG5bu5xsAJam5RkCYSjkSqZ1LotlWmISBQ/edit#heading=h.379ny8pm09k5

After converting it to markdown, certain cells contain text wrapped in `<code>` tags - but other cells have text wrapped in backticks. See attached file.

Actually, the `<code>` tags are working well for me - but the backticks are not. 

1. Is there some way that I could get it to generate with `<code>` tags only?
2. Can you shed any light on the cause of this behaviour?

Many, many thanks!

[campaign-fields.txt](https://github.com/evbacher/gd2md-html/files/3716292/campaign-fields.txt)

**Comment by evbacher** [comment]
Thanks for reporting this bug! 

We should be doing all HTML within the table, not Markdown. It seems that the problem starts after the table within the table. Will investigate.

**Comment by pcimring** [comment]
Many thanks, Ed

I was also wondering if the nested table was the cause of the issue.

*Question*: on what basis does it decide to mark the text as code (using
either <code> tags or back-ticks)? I'm wondering why so much of the text in
the table seems to get marked as code.

Thanks :)

**Comment by evbacher** [comment]
For any text that is a known constant-width font (currently Courier New, Consolas, Inconsolata, Roboto Mono, or Source Code Pro, we mark it as constant width. For Markdown, we'll use backticks (or ``` if the whole paragraph is constant-width). If it's HTML or in a table, we should be using HTML all the time. So something is wrong with the logic here, and it may be the table within a table that is messing things up. But we should be smarter about that too.

All the text in your table seems to be Consolas, so that explains the \<code> markup. If you change the font to something that is not constant-width, the table might convert just fine.

**Comment by pcimring** [comment]
Ah - many thanks for feedback.

We typically mark *only *variables and code snippets with backticks.

It will be interesting to see the output using a regular font in the source
table  - and a fixed font for variables and code snippets only.

I'm on leave this week, but will give it a try when I next have a chance...

Thanks :)

**Comment by evbacher** [comment]
Closing this for now, as constant-width fonts in tables _should_ be marked up with HTML &amp;code> tags in table.
