### ISSUE TITLE
In markdown conversion auto-correct whitespaces that break emphasis (bold/italics)

### ISSUE THREAD

**Issue by immitev** [evbacher/gd2md-html#53]
In Google docs, when using bold and italics, occasionally the formatting accidentally includes a space, and e.g. **word** gets converted to  `**word **` or `** word**` or `** word **`, which is not interpreted as emphasis in markdown.

During the process of conversion, it would be hopefully not difficult to check for whitespaces in the start of a bold/italics formatted section and if necessary move the unintentionally formatted section to the previous or next unformatted section.

**Comment by evbacher** [comment]
The latest version (1.0β20: Handle font-change runs with extra whitespace better (italic, bold, etc.).) should fix most of these problems where there's extra whitespace embedded in bold/italic formatting.

Please reopen if not.

There may be some edge cases of font formatting that cause trouble (like an italic run with an embedded bold run). But that's a different issue from the extra whitespace problem. So I'm going to close this bug and open a separate one if necessary for other edge cases.

Incremental change for the win!
