### ISSUE TITLE
Does not play well with Zotero data.

### ISSUE THREAD

**Issue by HughP** [evbacher/gd2md-html#54]
Zotero is a plugin for managing citations and bibliography in a document. The markdown does not seem to respect the links that Zotero makes.

**Comment by evbacher** [comment]
I am not familiar with Zotero or what it does with citation or bibliography links. Do you have an example doc with a link that you can share?

**Comment by HughP** [comment]
Yes I have a sample document I can share.  Do you have a resume with your gmail address to share? I can also share a privat github repo

**Comment by evbacher** [comment]
Closing this for now -- not sure about the details of what Zotero does. In general, we are trying to convert what you see in a Google Doc to the equivalent when rendered in Markdown/HTML. Trying to avoid non-obvious side effects or add specialized markup. (With the exception of definition lists, which Google Docs does not support natively.)

Please reopen if you have more details about what Zotero is doing.
