### ISSUE TITLE
Make the appscript code available?

### ISSUE THREAD

**Issue by caribu-zz** [evbacher/gd2md-html#56]
Hi,
is there any chance you could make the appscript code available. It would enable others to build on top of your solution. I would for example need a different way to deal with images...

Thanks for considering it...

Conrad

**Comment by dwalks12** [comment]
Hey @caribu-zz I made a quick plugin that works that you can probably add images onto here:
https://github.com/dwalks12/googledoc-to-md-to-html

It converts to markdown then markdown to html. Seems to work fairly well.

**Comment by caribu-zz** [comment]
Thanks!
This is really helpful. I will have to send the images and the html through an API, but this will save me a lot of work ...

**Comment by evbacher** [comment]
The code is now available. I will continue to update this repo as the addon is updated. Enjoy!
