### ISSUE TITLE
angle brackets showing as &lt;

### ISSUE THREAD

**Issue by angiejones** [evbacher/gd2md-html#58]
In Docs, I have:
`<br><img src="img1.png"/><br>`

Markdown is converting it to:
`<br>&lt;img src="img1.png"/>&lt;br>`

This used to work fine (last time I tried it was January 2020)

Note that the brackets work fine on the first `<br>` but break on the opening tag of the `<img>`. Similar happening with the closing tags.

**Comment by evbacher** [comment]
There's a new option, Render HTML tags, that should let <br><img src="img1.png"/><br>
pass through as is. (That should give you the same behavior you were seeing in January.)

By default, <br><img src="img1.png"/><br> should convert to 
&lt;br>&lt;img src="img1.png"/>&lt;br>

That seems to be a bug that I'll take a look at.

**Comment by evbacher** [comment]
Thanks for discovering and reporting this bug!

Latest version (Docs to Markdown 1.0β19) fixes the `<` conversion problem at the beginning of the line. You'll still need to select the `Render HTML tags` option if you want HTML to pass through without converting to `&lt;`.
