### ISSUE TITLE
Markdown[] ScriptError: Authorization is required to perform that action.

### ISSUE THREAD

**Issue by Merith-TK** [evbacher/gd2md-html#59]
![image](https://user-images.githubusercontent.com/10422110/77198298-f58b9300-6aa3-11ea-84c6-f0337e6eab2a.png)
I cant get this tool to work at all

**Comment by evbacher** [comment]
Can you share a (view-only) copy of a doc that causes this error, so we can investigate?

**Comment by Merith-TK** [comment]
sure, let me see if i still have it

**Comment by Merith-TK** [comment]
https://docs.google.com/document/d/1a5cVAS6SfQ3foQXE-sm3aM5d_OtU-TEEmFcrwJb75N8/edit?usp=sharing

**Comment by evbacher** [comment]
Thanks -- will check it out.

**Comment by evbacher** [comment]
I am able to convert a copy of your doc to Markdown and HTML successfully. Are you still having this problem? If so, please reopen.
