### ISSUE TITLE
Stripping white space from HTML tags leads to concatenated words

### ISSUE THREAD

**Issue by turnuptheac** [evbacher/gd2md-html#60]
First of all, thanks for developing this extension - it's a lifesaver and we use it regularly every week.

In #53 you worked on stripping whitespace from words. I understand the motivation for this (personally, our markdown interpreter renders `**word **` as intended). 

However, the fix has led to words being concatenated.

![image](https://user-images.githubusercontent.com/5273392/78801315-24e63f00-7982-11ea-87cf-7c09dc8bd57d.png)

For us, this renders as:
![image](https://user-images.githubusercontent.com/5273392/78801388-42b3a400-7982-11ea-9c2e-c4a2b824e9a3.png)

This also happens in the HTML conversion option:

![image](https://user-images.githubusercontent.com/5273392/78801531-71ca1580-7982-11ea-9c80-2d4acb4ae04c.png)

I'd suggest rolling back this change and revisiting the solution concept. One suggestion: maybe any stripped white space can be added outside the tag, eg:
`This is a bolded** word **and I like it.`
can turn to
`This is a bolded **word** and I like it.`

------
Ultimately, the bolded/italicized whitespace after a word is a natural consequence of how Google Docs works. Writers often bold/italicize by first selecting text with Ctrl+Shift, which naturally selects the space before or after:

![image](https://user-images.githubusercontent.com/5273392/78800165-bfde1980-7980-11ea-9d26-edd47723ebec.png)

**Comment by evbacher** [comment]
Sorry about that -- can you share a short doc that includes the error cases you mention?

I'll try to fix or consider reverting. Thanks!

**Comment by turnuptheac** [comment]
@evbacher Absolutely - [here's a sample doc](https://docs.google.com/document/d/1PmMlYRU8S34k1OTShWaVZqTLGombtile7DkiQV5c4G4/edit) with examples. Thanks for looking into this!

**Comment by evbacher** [comment]
Thanks for the sample doc (and for pointing out the bug). My fixes for the extra whitespace problem clearly are not working as well as I'd hoped. We still have some problems, but I've rolled back to the older version.

There may still be some problems with font changes, depending on how the selection was done -- I may investigate falling back to HTML for complicated font runs.

I'm closing this particular bug for now, but will open another against the font runs if one does not already exist. Feel free to send me additional edge cases if you find them!

**Comment by evbacher** [comment]
Note: rolled back the supposed fix for extra whitespace in font change runs in v1.0β22.

**Comment by turnuptheac** [comment]
@evbacher Thanks for the quick turnaround! I verify that the spaces are now back as intended.

**Comment by evbacher** [comment]
I am curious -- which Markdown parser/renderer are you using? Do you know what flavor of Markdown it implements? One problem, as you know, is that there are many Markdown "standards."

**Comment by turnuptheac** [comment]
We're using Mistune: https://github.com/lepture/mistune

We actually chose it specifically because it's very fault-tolerant and renders extra whitespace as the human intended, compared to say the normal python markdown lib.
