### ISSUE TITLE
About lines return after <p>

### ISSUE THREAD

**Issue by DBsoft95** [evbacher/gd2md-html#64]
Why do we always get a line break after a <p> tag like this:
<p>
My name is ...
</p>
instead of <p>My name is ...</p>
Thank you

**Comment by evbacher** [comment]
Is this causing a problem with the rendered HTML?

**Comment by DBsoft95** [comment]
Yes this poses a problem because by pasting the HTML result into an HTML Editor, the Editor adds a <br> tag like this:
<p>
my name is ...
</p>
The Editor transforms this into:
<p><br>
my name is ...
</p>
And I get a blank line before each paragraph.
It would be better to get the following result from Docs to Markdown:
<pre>  <p>my name is ...</p><p>jkhk kjhkjk</p></pre>
What do you think ?
Thank you

**Comment by DBsoft95** [comment]
Sorry, the tags were not displayed.
Yes this poses a problem because by pasting the HTML result without an HTMl Editor, the editor adds a <br> tag like this:
&lt;p&gt;
my name is ...
&lt;/p&gt;
The Editor transforms this into:
&lt;p&gt; &lt;br&gt;
my name is ...
&lt;/p&gt;
And I get a blank line before each paragraph
It would be better to get the following result from Docs to Markdown:
  &lt;p&gt; my name is ... &lt;/p&gt; &lt;p&gt; jkhk kjhkjk &lt;/p&gt;
What do you think ?
Thank you

**Comment by evbacher** [comment]
<p>
my name is ...
</p>

is valid HTML. If you want to clean it up after conversion, you can use something like Tidy or HTML Tidy.

If your editor is adding a &lt;br> tag, that seems like a bug with the editor.
