### ISSUE TITLE
Installation doesn't seem to take

### ISSUE THREAD

**Issue by jenlanu** [evbacher/gd2md-html#66]
I attempted to install from https://gsuite.google.com/marketplace/app/docs_to_markdown/700168918607 by clicking the Install button on that page.

It prompts me to authenticate, so I used my g-suite account.

After it finished the install page still shows the "Install" button, and opening a Google doc (on the same g-suite account) there is no option in the Add-Ons menu for this.

I tried refreshing that google doc page. I also tried closing that tab and reopening the google doc fresh from Drive.

I don't know what else to try.

**Comment by jenlanu** [comment]
I decided to try to do the install from within the doc by searching for this add-on. That took me through a different g-suite authentication and approval process which seemed to do it right.

**Comment by evbacher** [comment]
Sorry you had trouble with this. Some people have been reporting authentication issues with add-ons when they're logged in with more than one Google/Gmail account. Not sure if that was an issue in this case.

**Comment by jenlanu** [comment]
Yes, that applies here. My main login is my personal one and despite switching to my g-suite account during install it didn't work. The way I got it to work was to start from my g-suite google doc and use the add-on menu there to find and install.
