### ISSUE TITLE
Doesn't convert links?

### ISSUE THREAD

**Issue by george08** [evbacher/gd2md-html#71]
Hi ed - thanks very much for the tool!

I've added links in the Google doc but they don't seem to get made in the Markdown output... any idea why?

Thanks!

**Comment by evbacher** [comment]
Hyperlinks should convert to Markdown or HTML links. Can you share a link to a copy of the doc where the trouble is happening? (view permission is fine -- I can make a copy)

**Comment by evbacher** [comment]
I cannot reproduce this error. If it's still happening for you, please share a view-only copy of a doc where it happens, and I'll check it out (and reopen this bug). Thanks!
