### ISSUE TITLE
"Wrap HTML" produces invalid code on non-breaking newlines.

### ISSUE THREAD

**Issue by giuspe** [evbacher/gd2md-html#72]
### description of the problem

when converting to HTML, flagging the option *"Wrap HTML"* produces invalid code when processing non-breaking newlines; 
the bug **doesn't occur** with breaking newlines (that correctly generate `<p></p>`).

### how to reproduce

1. open a document
2. write a line of text
3. insert one or more non-breaking newlines (`SHIFT+ENTER`)
4. flag the "Wrap HTML" option on HTML conversion
5. convert the document to HTML

### expected result

```
[...]
<br />
[...]
```

# actual result

```
[...]
&lt;br>
[...]
```

**Comment by evbacher** [comment]
Thanks for reporting! I'll try to fix this as soon as I get a chance.

**Comment by evbacher** [comment]
@giuspe: thanks again for  finding this bug (not just for Wrap HTML, but for all HTML, I think). The latest version (1.0β26: Render soft line breaks correctly in HTML (<br> not &lt;br>). ) should fix this, but please let me know if you notice any related problems and reopen.

**Comment by giuspe** [comment]
hi @evbacher , and thanks for the lightning fast fix!

I can confirm, the problem doesn't occur anymore - at least for my test setup, Brave 1.9.76  81.0.4044.138 (64-bit) on Fedora 32.

thanks again for your work!

**Comment by evbacher** [comment]
Thanks for confirming. You caught me on a Saturday when I didn't have much to do. I'm not always that fast :)
