### ISSUE TITLE
Disable Images

### ISSUE THREAD

**Issue by ncammarata** [evbacher/gd2md-html#73]
Hi -- amazing plugin!

I'm wondering if it's possible to simply ignore images in the doc -> markdown process. I'm writing an html (distill.pub) paper with interactive figures, and I have images of the figures in my google docs and real figures in my html paper. It's a bit of a weird use-case, but I'd love if it was possible!

Nick

**Comment by evbacher** [comment]
@ncammarata:
It's kind of an edge case, but since we can't do much directly with images, it might be a good option. Would you want any kind of marker in the converted text, or just ignore the images and drawings completely?

**Comment by ncammarata** [comment]
Ignore completely but I don't think it's worth the code surface area of supporting my weird case

**Comment by evbacher** [comment]
Closing this for now. I think @ncammarata forked and fixed it in their own version.Iif it becomes a greater need, we can reopen.
