### ISSUE TITLE
Error message TypeError: Cannot find function getNestingLevel in object Paragraph.

### ISSUE THREAD

**Issue by BenLinders** [evbacher/gd2md-html#74]
When I try to convert my Google doc to HTML I get:

TypeError: Cannot find function getNestingLevel in object Paragraph.

Conversion to Markdown seems to work ok.

Any idea what might cause this?

**Comment by evbacher** [comment]
My bad - sorry about the breakage. It should be working properly now if you reload the Doc and convert.

**Comment by BenLinders** [comment]
Works ok now, thanks Ed for your quick response and action
