### ISSUE TITLE
Markdown bold broken at newline

### ISSUE THREAD

**Issue by Morgan10E** [evbacher/gd2md-html#77]
If the document looks like this:
**Here's some bold text**
Here's some stuff after the newline

The markdown will be this:
```
**Here's some bold text \
**Here's some stuff after the newline
```

If the document looks like this:
**Here's some bold text again**
**One more** then not bold

The markdown is this:
```
**Here's some bold text again \
One more** then not bold
```

**Comment by evbacher** [comment]
You have a soft linebreak (shift-enter) after the first line. Docs to Markdown doesn't continue the font change after that. If you make the second line a new paragraph, it will work (but you'll get a new paragraph):

```
With soft linebreak:

**Here's some bold text again \
One more** then not bold

With newline

**Here's some bold text again**

**One more** then not bold
```
