### ISSUE TITLE
Mixing italics and bold breaks markdown formatting.

### ISSUE THREAD

**Issue by q00u** [evbacher/gd2md-html#8]
Because italics are currently being converted to * rather than _, if you **bold** a word inside an _italicized sentenced_, the first * of the ** bold _closes_ the italics. Then you have a word that looks like \*this** and the sentence ends like this.*

Example:
Input: \*Mixed \*\*format\*\* test.\*
Output: *Mixed* \*format\*\* test.\*

(On _some_ sites like Reddit. It works how it **should** here on github.)

Two ways to fix it would be to convert italics to _ instead of *, or to fully format mixed cases.

\_Mixed \*\*format\*\* test.\_
\*Mixed\* \*\*\*format\*\*\* \*test.\*

**Comment by evbacher** [comment]
Excellent point -- thanks! We do deal with some mixed content by falling back to HTML, but this is a bug. I'll try using _ for italic and ** for bold.

**Comment by evbacher** [comment]
The latest version (1.0β8) uses _ to denote italic and ** for bold. Please open a new bug if you find any problems.
