### ISSUE TITLE
Code blocks: HTML tags are encoded

### ISSUE THREAD

**Issue by dotNetkow** [evbacher/gd2md-html#81]
(might not need a separate issue. [related](https://github.com/evbacher/gd2md-html/issues/80))

When converting from plain text to markdown, the HTML within a code block is encoded:

```html

&lt;!-- Template with Ionic Framework UI components -->

&lt;template>

  &lt;ion-app>

    &lt;ion-router-outlet />

  &lt;/ion-app>

&lt;/template>

```

Would like it to be:
```
<!-- Template with Ionic Framework UI components -->
<template>
  <ion-app>
    <ion-router-outlet />
  </ion-app>
</template>
```

**Comment by evbacher** [comment]
When I convert a test document to Markdown that has this code block (in Consolas), it leaves the tags alone (it does not convert the < to `&lt;`:

```
<!-- Template with Ionic Framework UI components -->
<template>
  <ion-app>
    <ion-router-outlet />
  </ion-app>
</template>
```

Please reopen if this is still happening.
