### ISSUE TITLE
Google Docs add-ons are greyed out

### ISSUE THREAD

**Issue by alfken** [evbacher/gd2md-html#83]
"It requires no other permissions." - Is this still true?
 - My Google Docs add-ons are greyed out - https://i.imgur.com/XPIWXq9.png.
 - So I google-searched for {"google docs" add-ons greyed out} and found https://i.imgur.com/vpCBFbx.png.
 - So I typed 'admin.google.com' in the URL area of Google Chrome - https://i.imgur.com/fVd86Ge.png.
 - I don't have a "Google Workspace account" and I have never heard of it before, so I gave up! :(

**Comment by evbacher** [comment]
It sounds like you may be part of an organization that has a Google Workspace (formerly GSuite) account. The admin can allow (or disallow) users to install third-party add-ons, which may be what is happening here.

If you are using your personal Google account, you should be able to install any add-on you want.

**Comment by alfken** [comment]
It works now! (I _**am**_ using my personal account.)
I can still not directly convert the document I tried yesterday ...  
But it came to my mind that I am not the owner of that document. So I downloaded it (in `.docx` format),
 and uploaded it into my own Google Drive. I also un-installed and re-installed `Docs to Markdown`.
 (The first re-installation failed, but the second was successful.)
I am sorry for reporting a "bug" which apparently is not a bug at all, but rather reflects my ignorance
 on how to use this very fine extension.
The only (but overall very minor) "complaint" I can think of right now, is that I would have preferred
 the window containing the converted code to be a little bit wider, https://i.imgur.com/0lVO0lo.png.
Many, many thanks for providing this wonderfully helpful and extremely time-saving extenstion!
👍

**Comment by evbacher** [comment]
Thanks for reporting this bug -- it's good to be aware of problems that people are running into, even if they are not caused directly by Docs to Markdown.

Glad you were able to figure this out! Google Docs add-ons sometimes have confusing behavior, particularly when it's related to ownership and permissions. I'm not sure why you needed to install Docs to Markdown more than once, but I'll note that's yet another potential issue with add-ons.

As for the window, I'd like it to be wider too, but I tried to make it wider a while ago, and I believe it's at the max width allowed now. Google Docs doesn't want to give up too much page space to add-ons!

**Comment by alfken** [comment]
> As for the window, I'd like it to be wider too, but I tried to make it wider a while ago, and I believe it's at the max width allowed now. Google Docs doesn't want to give up too much page space to add-ons!
 - Yes, I suspected something like that. Thanks again! :-)
