### ISSUE TITLE
adding Jira 's Text Formatting notation

### ISSUE THREAD

**Issue by arsenyspb** [evbacher/gd2md-html#85]
Thanks for wonderful project! Atlassian Jira uses a slightly [different notation](https://jira.atlassian.com/secure/WikiRendererHelpAction.jspa?section=all). Do you think its possible to combine (add a "Button") in to Docs to Markdown? It's specifically important when one authors JSON rules for Jira Automation. Many coffees worth of kudos!

**Comment by evbacher** [comment]
Jira's notation is really a different markup language. You could fork this project and use it out output the Jira notation, but I do not currently have the bandwidth to do that. Feel free to ping me if you need some advice on parsing the Google Doc and outputting another markup format.
