### ISSUE TITLE
Unable to download in Google Marketplace

### ISSUE THREAD

**Issue by allisonburtch** [evbacher/gd2md-html#86]
I'm attempting to download the Docs to Markdown add-on at this [link](https://gsuite.google.com/marketplace/app/docs_to_markdown/700168918607). I get a notice that says the app is unavailable for download because `Install disabled by admin`. Has anyone else received this error? 

Thank you for developing this, would really love to try it.

**Comment by evbacher** [comment]
I am assuming (from that error message) that your org has a Google Workplace account. You'll probably need to contact your admin to figure out if you can install it or not (or if they need to install/enable it).

You may be able to install it from your personal Google/Gmail account.

**Comment by allisonburtch** [comment]
Thank you, you're completely correct. I'll have to contact IT admins.
