### ISSUE TITLE
Convert is not showing in menu after first install

### ISSUE THREAD

**Issue by jharris1679** [evbacher/gd2md-html#87]
Maybe my document isn't compatible, or something, but the menu that is supposed to have the Convert option only has one option, Help. 

Could this be because I am a domain administrator on my org's google account? I saw a note that said individual installation may not work for these accounts, but I tried anyway and assumed I would be blocked from installing. Instead, the install was successful, but now I can't seem to convert a doc.

**Comment by evbacher** [comment]
I'm not sure what the behavior is if you do an individual install of an add-on even though your org has a Google Workplace account.  Did you install it under your personal Google/Gmail account? Try opening an incognito window and signing into your personal account (assuming you installed using that account).

**Comment by jharris1679** [comment]
Hey, thanks for the reply. I installed it under my work gmail account. I did end up getting it to work by doing a domain install for my whole google workspace. I guess the behaviour of an individual install on a workspace admin account is that the add on can't get permission to read the doc, so the Convert option doesn't show in the menu. Feel free to close this.
