### ISSUE TITLE
Sidebar won't load / connect

### ISSUE THREAD

**Issue by mckenziescott13** [evbacher/gd2md-html#88]
I've installed the plug-in to my personal gmail/gdrive account. However, when I click "Convert" the side bar pops up but is grey and when I hover my mouse over the sidebar it just says "drive.google.com refused to connect."

![image](https://user-images.githubusercontent.com/56656544/105381607-2f09bf00-5bdd-11eb-8470-ea4daac0574d.png)

**Comment by evbacher** [comment]
See
https://github.com/evbacher/gd2md-html/wiki#drivegooglecom-refused-to-connect

- Ed

**Comment by mckenziescott13** [comment]
That definitely did the trick, Ed. Apologies for not seeing that earlier in the wiki. I appreciate your reply!
