### ISSUE TITLE
Line breaks inserted in code samples

### ISSUE THREAD

**Issue by angiejones** [evbacher/gd2md-html#89]
For code snippets, a blank line is inserted after each line of code.

For example, given this in Google Doc:

```
  @Order(1)
  void thirdTest() {
      System.out.println("This is the third test method");
  }
```

it converts to:

```    
    @Order(1)

    void thirdTest() {

        System.out.println("This is the third test method");

    }
```

**Comment by evbacher** [comment]
I pasted your code sample into a Google Doc, changed it to Courier New, and I am not seeing the behavior you describe. Can you share (view-only is fine) a copy of a Doc that exhibits this problem so I can figure out what's going on? ed.bacher at gmail.com

**Comment by angiejones** [comment]
ah I didn't realize I needed to change the font to Courier New. Mine was in Ariel. After changing it, the output no longer contains extra line breaks.

**Comment by evbacher** [comment]
Yes, the converter uses constant-width fonts (like Courier New, Consolas, Roboto Mono) to determine if it's a code block. Otherwise, it just treats them as regular paragraphs.
