### ISSUE TITLE
Superscript is being converted to html when you select markdown.

### ISSUE THREAD

**Issue by q00u** [evbacher/gd2md-html#9]
Currently, superscripted text is being wrapped in `<sup></sup>` blocks when markdown conversion is selected.

Superscript is not part of the canonical markdown specifications, so it _should_ be ignored, or converted to ^. It should _not_ be converted to html.

**Comment by evbacher** [comment]
I don't think Markdown was intended to replace HTML. In cases where Markdown doesn't handle formatting, it's permissible to use HTML Markup. As [John Gruber says here](https://daringfireball.net/projects/markdown/syntax#html),

- For any markup that is not covered by Markdown’s syntax, you simply use HTML itself. There’s no need to preface it or delimit it to indicate that you’re switching from Markdown to HTML; you just use the tags.

Are you using superscripts to indicate exponentiation?
