### ISSUE TITLE
< not converted to markdown

### ISSUE THREAD

**Issue by sancelot** [evbacher/gd2md-html#91]
When converting to markdown, < is converted as `&lt;`

**Comment by evbacher** [comment]
Do you mean that < is converted to &amp;lt? If so, that is working as intended. There is an option to render HTML tags (see https://github.com/evbacher/gd2md-html/wiki#options) that will leave them alone.

**Comment by sancelot** [comment]
Yes, I will correct the question . and try it.

**Comment by misseuropa** [comment]
This is going to sound funny but < is converted to &lt; and > stays > in converting to markdown. I'm def. going to use the render HTML tags (because that's what I need), but I want to let you know in case it's a place for improvement.

**Comment by evbacher** [comment]
There is actually no need to convert the > sign, as long as the opening tag < is converted to `&lt;`. This keeps the Markdown source as simple as possible.

If you really do want to render the HTML tags, then you can choose that option.
