### ISSUE TITLE
Colour is not converting (HTML or MD)

### ISSUE THREAD

**Issue by je5s** [evbacher/gd2md-html#92]
Formatting text with different colours should carry this colour forward when converting, but it doesn't.

For example, to emphasize a bullet point with with red text or green text, it should be wrapped in a span with 'style="color: ${color}"'

**Comment by evbacher** [comment]
We have considered (and occasionally tried) considering styles and colors, but it makes the code complex and slows down the addon. See this section of the [dev guide](https://github.com/evbacher/gd2md-html/blob/master/dev.md#no-fancy-formatting) for more information.
