### ISSUE TITLE
google drive refused to connect

### ISSUE THREAD

**Issue by ZakGhost354313** [evbacher/gd2md-html#98]
When i try to open the addon in google docs it shows a little side window showing a grey screen saying, 'drive.google.com refused to connect'.

![image](https://user-images.githubusercontent.com/68399876/133531981-f7502179-f0c6-45ed-8d34-ed65e8ca5bff.png)

full code on the image is located [here](https://gist.github.com/ZakGhost354313/68fac856e5c0d1207834e16a468c5a96)

**Comment by evbacher** [comment]
This is a known issue for Google add-ons when you're logged in to multiple Google accounts. See this troubleshooting item in our docs: https://github.com/evbacher/gd2md-html/wiki#drivegooglecom-refused-to-connect
